--- 
title: "BIA1401 2026 - Introduction à R"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
---

# Introduction

##  Aperçu du cours

Ce guide a été rédigé à l’intention des étudiantes et étudiants du cours BIA104 afin de les familiariser avec l’utilisation du langage de programmation R et de l’IDE RStudio pour la manipulation de tableaux de données.

1. La première section [Introduction à R et RStudio] présente brièvement R et RStudio. 

2. La seconde section [Utiliser RStudio et R Markdown] introduit quelques notions de base en R et explique comment élaborer des scripts avec RStudio en format R ou R Markdown. 

3. La troisième section [Script pour BLAST] comprend un petit script R que les étudiants doivent utiliser afin d'obtenir, pour chacun de leurs inconnus, la séquence d'acides nucléiques correspondant au gène ARNr 16S. Les étudiants pourront ensuite soumettre ces séquences à l'outil *Basic Local Alignment Search Tool* ([BLAST](https://blast.ncbi.nlm.nih.gov/Blast.cgi)) du National Center for Biotechnology Information (NCBI) afin d'attribuer une classification taxonomique à chacun de leurs inconnus.

## Installer R et RStudio 

R est disponible gratuitement pour les systèmes d'exploitation Windows, Mac et Linux sur le [site officiel des archives de R](https://cloud.r-project.org/). 

Une fois R installé, vous pouvez procéder à l'installation de [RStudio](https://posit.co/download/rstudio-desktop/)

## Références et liens utiles 

[An Introduction to R](https://intro2r.com/)

[Introduction à R par GRICAD Grenoble Alpes Recherche - Infrastructure de Calcul Intensif et de Données](https://formations_r.gricad-pages.univ-grenoble-alpes.fr/ced_intror/)

[Série d’ateliers R du CSBQ](https://r.qcbs.ca/fr/workshops/)

[Data Science avec R](https://bookdown.org/fousseynoubah/dswr_book/objets-dans-r.html) (Je recommande spécialement le **Chapitre 3 Objets dans R** et le **Chapitre 4 S’exprimer dans R**)

